import 'package:flutter/material.dart';
import 'heart_risk_model.dart';
import 'heart_risk_results.dart';

class HeartRiskForm extends StatefulWidget {
  final String? profileName;
  final int? profileAge;
  final String? profileGender;
  final bool? profileFamilyHistory;

  const HeartRiskForm({
    super.key,
    this.profileName,
    this.profileAge,
    this.profileGender,
    this.profileFamilyHistory,
  });

  @override
  _HeartRiskFormState createState() => _HeartRiskFormState();
}

class _HeartRiskFormState extends State<HeartRiskForm> {
  final _formKey = GlobalKey<FormState>();
  late HeartRiskData _formData;

  final List<String> _alcoholOptions = ['none', 'light', 'moderate', 'heavy'];
  final List<String> _dietOptions = ['healthy', 'average', 'nonhealthy'];

  @override
  void initState() {
    super.initState();
    _formData = HeartRiskData(
      age: widget.profileAge ?? 40,
      sex: widget.profileGender ?? 'Male',
      cholesterol: 200,
      bloodPressure: '120/80',
      heartRate: 72,
      diabetes: false,
      familyHistory: widget.profileFamilyHistory ?? false,
      smoking: false,
      obesity: false,
      alcoholConsumption: 'none',
      exerciseHours: 3.5,
      diet: 'average',
      previousHeartProblems: false,
      medicationUse: false,
      stressLevel: 5,
      sedentaryHours: 8,
      income: 50000,
      bmi: 25,
      triglycerides: 150,
      physicalActivityDays: 3,
      sleepHours: 7,
    );
  }

  void _updateFormData(HeartRiskData newData) {
    setState(() {
      _formData = newData;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Heart Attack Risk Assessment')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildNumberInput(
                'Age',
                (value) => _updateFormData(HeartRiskData(
                  age: value.toInt(),
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.age.toDouble(),
              ),
              _buildDropdown(
                'Sex',
                ['Male', 'Female'],
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: value!,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.sex,
              ),
              _buildNumberInput(
                'Cholesterol (mg/dL)',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: value,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.cholesterol,
              ),
              _buildTextInput(
                'Blood Pressure (e.g. 120/80)',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: value,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.bloodPressure,
              ),
              _buildNumberInput(
                'Heart Rate (bpm)',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: value.toInt(),
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.heartRate.toDouble(),
              ),
              _buildSwitch(
                'Diabetes',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: value,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.diabetes,
              ),
              _buildSwitch(
                'Family History of Heart Disease',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: value,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.familyHistory,
              ),
              _buildSwitch(
                'Smoking',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: value,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.smoking,
              ),
              _buildSwitch(
                'Obesity',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: value,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.obesity,
              ),
              _buildDropdown(
                'Alcohol Consumption',
                _alcoholOptions,
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: value!,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.alcoholConsumption,
              ),
              _buildNumberInput(
                'Exercise Hours Per Week',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: value,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.exerciseHours,
              ),
              _buildDropdown(
                'Diet',
                _dietOptions,
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: value!,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.diet,
              ),
              _buildSwitch(
                'Previous Heart Problems',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: value,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.previousHeartProblems,
              ),
              _buildSwitch(
                'Medication Use',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: value,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.medicationUse,
              ),
              _buildSlider(
                'Stress Level (1-10)',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: value.toInt(),
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.stressLevel.toDouble(),
                1,
                10,
              ),
              _buildNumberInput(
                'Sedentary Hours Per Day',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: value,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.sedentaryHours,
              ),
              _buildNumberInput(
                'BMI',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: value,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.bmi,
              ),
              _buildNumberInput(
                'Triglycerides (mg/dL)',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: value,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: _formData.sleepHours,
                )),
                _formData.triglycerides,
              ),
              _buildNumberInput(
                'Physical Activity Days Per Week',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: value.toInt(),
                  sleepHours: _formData.sleepHours,
                )),
                _formData.physicalActivityDays.toDouble(),
              ),
              _buildNumberInput(
                'Sleep Hours Per Day',
                (value) => _updateFormData(HeartRiskData(
                  age: _formData.age,
                  sex: _formData.sex,
                  cholesterol: _formData.cholesterol,
                  bloodPressure: _formData.bloodPressure,
                  heartRate: _formData.heartRate,
                  diabetes: _formData.diabetes,
                  familyHistory: _formData.familyHistory,
                  smoking: _formData.smoking,
                  obesity: _formData.obesity,
                  alcoholConsumption: _formData.alcoholConsumption,
                  exerciseHours: _formData.exerciseHours,
                  diet: _formData.diet,
                  previousHeartProblems: _formData.previousHeartProblems,
                  medicationUse: _formData.medicationUse,
                  stressLevel: _formData.stressLevel,
                  sedentaryHours: _formData.sedentaryHours,
                  income: _formData.income,
                  bmi: _formData.bmi,
                  triglycerides: _formData.triglycerides,
                  physicalActivityDays: _formData.physicalActivityDays,
                  sleepHours: value,
                )),
                _formData.sleepHours,
              ),
              const SizedBox(height: 20),
              Center(
                child: ElevatedButton(
                  onPressed: _submitForm,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.blue,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(
                      horizontal: 32,
                      vertical: 16,
                    ),
                  ),
                  child: const Text(
                    'Calculate Risk',
                    style: TextStyle(fontSize: 16),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildNumberInput(String label, Function(double) onChanged, double value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: TextFormField(
        decoration: InputDecoration(
          labelText: label,
          border: const OutlineInputBorder(),
        ),
        keyboardType: TextInputType.number,
        initialValue: value.toString(),
        onChanged: (value) {
          final num = double.tryParse(value);
          if (num != null) onChanged(num);
        },
      ),
    );
  }

  Widget _buildTextInput(String label, Function(String) onChanged, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: TextFormField(
        decoration: InputDecoration(
          labelText: label,
          border: const OutlineInputBorder(),
        ),
        initialValue: value,
        onChanged: onChanged,
      ),
    );
  }

  Widget _buildDropdown(String label, List<String> options, Function(String?) onChanged, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: DropdownButtonFormField<String>(
        decoration: InputDecoration(
          labelText: label,
          border: const OutlineInputBorder(),
        ),
        initialValue: value,
        items: options.map((String value) {
          return DropdownMenuItem<String>(
            value: value,
            child: Text(value[0].toUpperCase() + value.substring(1)),
          );
        }).toList(),
        onChanged: onChanged,
      ),
    );
  }

  Widget _buildSwitch(String label, Function(bool) onChanged, bool value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Row(
        children: [
          Expanded(child: Text(label)),
          Switch(value: value, onChanged: onChanged),
        ],
      ),
    );
  }

  Widget _buildSlider(String label, Function(double) onChanged, double value, double min, double max) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label),
          Slider(
            value: value,
            min: min,
            max: max,
            divisions: (max - min).toInt(),
            label: value.round().toString(),
            onChanged: onChanged,
          ),
        ],
      ),
    );
  }

  void _submitForm() {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => HeartRiskResults(data: _formData),
        ),
      );
    }
  }
}
